Repository speedpratik/speedpratik, pull requests merged in 2022-05, with the labels that each got.

#2 Added Oauth2, started the main page content (Frontend) | Waiting for API.
  README.md
  assets/css/login.css
  assets/css/main.css
  assets/css/mainPage.css
  assets/css/navbar.css
  components/Leaderboard.vue
  components/MainContent.vue
  components/NavbarSP.vue
  middleware/restrict-to-auth.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/Login.vue
  pages/index.vue
  static/background.svg
  static/board.svg
  static/prog.jpg
  store/store.js
  yarn.lock
Labels: enhancement

#4 Added dropdown + logout
  assets/css/main.css
  assets/css/navbar.css
  components/NavbarSP.vue
  nuxt.config.js
  pages/Login.vue
  plugins/click-outside.js
  static/prog.jpg
Labels: enhancement

#3 Users API
  .gitignore
  api/database/sqlite.js
  api/docs/.nojekyll
  api/docs/_navbar.md
  api/docs/_sidebar.md
  api/docs/achievements.md
  api/docs/attempts.md
  api/docs/index.html
  api/docs/introduction.md
  api/docs/leaderboards.md
  api/docs/subjects.md
  api/docs/trophies.md
  api/docs/users.md
  api/index.js
  api/users.js
  docs/README.md
  docs/_navbar.md
  docs/_sidebar.md
  nuxt.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#5 Moved docs folder
  api/docs/_navbar.md
  api/index.js
  docs/.nojekyll
  docs/_navbar.md
  docs/_sidebar.md
  docs/achievements.md
  docs/attempts.md
  docs/index.html
  docs/introduction.md
  docs/leaderboards.md
  docs/subjects.md
  docs/trophies.md
  docs/users.md
Labels: documentation

#6 Subjects api
  api/database/sqlite.js
  api/database/sqlite/exercises.js
  api/database/sqlite/subjects.js
  api/database/sqlite/users.js
  api/exercises.js
  api/index.js
  api/subjects.js
  api/users.js
  docs/_navbar.md
  docs/_sidebar.md
  docs/exercises.md
  docs/index.html
  docs/leaderboards.md
  docs/subjects.md
  docs/users.md
Labels: documentation, enhancement

#8 Fixed Asserts type
  api/database/sqlite/exercises.js
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#9 Added API in IDE
  pages/ide.vue
Labels: enhancement

#10 IDE almost finished (Add the ability to validate and confetti + submit to api)
  assets/css/ide.css
  assets/css/mainPage.css
  pages/ide.vue
  sqlite.db-journal
Labels: enhancement

#13 Deployement
  .env.example
  .eslintignore
  .github/workflows/docker-publish.yml
  Dockerfile
  api/database/sqlite/exercises.js
  assets/css/ide.css
  assets/css/main.css
  assets/css/mainPage.css
  docs/attempts.md
  nuxt.config.js
  package.json
  pages/ide.vue
  plugins/vue-js-modal.js
  yarn.lock
Labels: documentation, enhancement

#14 Hotfix docker and CSS
  Dockerfile
  assets/css/mainPage.css
Labels: bug

#17 Deployment
  .env.example
  .eslintignore
  .github/workflows/ci.yml
  .github/workflows/docker-publish.yml
  Dockerfile
  package-lock.json
  package.json
Labels: bug, enhancement

#16 Submissions api
  api/database/sqlite.js
  api/database/sqlite/exercises.js
  api/database/sqlite/subjects.js
  api/database/sqlite/submissions.js
  api/database/sqlite/users.js
  api/index.js
  api/submissions.js
  docs/_sidebar.md
  docs/exercises.md
  docs/introduction.md
  docs/subjects.md
  docs/submissions.md
  docs/users.md
Labels: enhancement

#19 Hotfixes Submissions API Endpoint
  api/database/sqlite/submissions.js
  api/submissions.js
Labels: bug

#20 Advancements IDE
  middleware/restrict-to-auth.js
  pages/ide.vue
Labels: enhancement

#21 IDE officially done | Bug hunt to do on it
  README.md
  assets/css/main.css
  pages/ide.vue
Labels: enhancement

#22 Submissions types
  api/database/sqlite/submissions.js
  api/submissions.js
  docs/submissions.md
Labels: documentation, enhancement

#25 Advancements main & API
  assets/css/main.css
  docs/submissions.md
  nuxt.config.js
  package.json
  pages/ide.vue
  pages/index.vue
  plugins/api.js
  plugins/axios.js
  yarn.lock
Labels: bug, enhancement

#28 Advancements
  assets/css/ide.css
  pages/ide.vue
  plugins/api.js
Labels: bug, enhancement

#29 Revert "API Token Authorization"
  .env.example
  api/index.js
  plugins/axios.js
Labels: enhancement

#32 Test docker
  api/index.js
Labels: bug

#33 Hotfix API (Rej)
  plugins/api.js
Labels: bug

#34 Cool avancements
  api/submissions.js
  assets/css/ide.css
  assets/css/main.css
  assets/css/profile.css
  components/StatsWindow.vue
  nuxt.config.js
  pages/index.vue
  pages/profile.vue
  plugins/axios.js
Labels: enhancement

#35 Hotfix CSS 🤨🤨🤨🤨🤨👍🧊🧊👍📦🗿🎉🎉🎉😳💀💀💀😳🗿🗿
  assets/css/ide.css
  assets/css/main.css
Labels: bug

#36 Forgot WHERE statement in SQL Update command, you know the rest
  api/database/sqlite/users.js
Labels: bug

#37 Fast css fixes username in navbar & profile
  assets/css/navbar.css
  assets/css/profile.css
  static/bg.svg
Labels: enhancement

#38 Fixed IDs and css ⚠️
  assets/css/ide.css
  pages/ide.vue
Labels: bug

#42 Deploy Fixes ⚠️
  README.md
  assets/css/profile.css
  pages/Login.vue
  pages/ide.vue
  pages/index.vue
  pages/profile.vue
  plugins/api.js
Labels: enhancement

#43 Added ability to print even if error
  pages/ide.vue
Labels: bug

#45 Fix exercises (Took difficulty 2 even if not daily)
  pages/index.vue
Labels: bug
